### ISSUE TITLE
Implement the end screen

### ISSUE THREAD

**Issue by Eitu33** [Eitu33/mazehem#2]
## Context
The game currently has neither a winning condition event or a way to restart a game.

## TODO
- [ ] Send an event once a player reaches the goal
- [ ] Display an end screen when the event has been received
- [ ] Display which player has won
- [ ] `Back to lobby` button (or `Restart` if lobby is not implemented yet)
