### ISSUE TITLE
Validate client connection

### ISSUE THREAD

**Issue by Eitu33** [Eitu33/mazehem#3]
## Context
No events are retrieved on the client's side after it tried connecting to the server. We never know if it actually connected or not.

## TODO
- [x] Send a message from the server after a connection has been established
- [x] Retrieve the message
- [x] Stop the client and return an error if the message was not received
