### ISSUE TITLE
Improve maze generation

### ISSUE THREAD

**Issue by Eitu33** [Eitu33/mazehem#4]
## Context
The current maze generation uses Prim's algorithm but choses the candidates through RNG.

## TODO
- [ ]  Search for ways to improve the maze complexity
- [ ] Keep it optimized
- [ ] Make the generation equally balanced for the 4 players
