### ISSUE TITLE
Implement handshake protocol

### ISSUE THREAD

**Issue by Eitu33** [Eitu33/mazehem#5]
## TODO
- [x] Generate a private key in the server
- [x] Send the key when the client is trying to connect
- [x] Encrypt client's connection message
- [x] Decrypt it in the server
- [x] Ban ips that were not verified

**Comment by Eitu33** [comment]
I have decided to remove the handshake protocol. I realized after implementing it that it was not necessary because of how everything had been implemented so far. An ip that connected to the server without using the game client will only take a player slot if the lobby is not full, and the only packets the server will ever read from a client (game or not) are SerKey inputs (right, bot, left, right).
